// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEUABq5C7jSQFBDvq2QmRCmiUaIPuouhw',
    appId: '1:1067988700909:web:f90b722643f81ee6a646e4',
    messagingSenderId: '1067988700909',
    projectId: 'brew-crew-a2975',
    authDomain: 'brew-crew-a2975.firebaseapp.com',
    storageBucket: 'brew-crew-a2975.firebasestorage.app',
    measurementId: 'G-906Z4QXE6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHUVw7cDhy007BrMFipYyfMcnEdS4Nuhc',
    appId: '1:1067988700909:android:16432c30858a0bada646e4',
    messagingSenderId: '1067988700909',
    projectId: 'brew-crew-a2975',
    storageBucket: 'brew-crew-a2975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLBNgezTrgjo0Z5CW6ADxLrjxi34JuxB4',
    appId: '1:1067988700909:ios:c57bbaaf3ebb0a36a646e4',
    messagingSenderId: '1067988700909',
    projectId: 'brew-crew-a2975',
    storageBucket: 'brew-crew-a2975.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLBNgezTrgjo0Z5CW6ADxLrjxi34JuxB4',
    appId: '1:1067988700909:ios:c57bbaaf3ebb0a36a646e4',
    messagingSenderId: '1067988700909',
    projectId: 'brew-crew-a2975',
    storageBucket: 'brew-crew-a2975.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEUABq5C7jSQFBDvq2QmRCmiUaIPuouhw',
    appId: '1:1067988700909:web:520de95a6306cfbea646e4',
    messagingSenderId: '1067988700909',
    projectId: 'brew-crew-a2975',
    authDomain: 'brew-crew-a2975.firebaseapp.com',
    storageBucket: 'brew-crew-a2975.firebasestorage.app',
    measurementId: 'G-45BTJFDCWT',
  );
}
